[project]
name = "agentic-sls"
version = "0.0.1"
description = "Agentic process optimization for selective laser sintering (SLS) additive manufacturing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.12.3",
    "requests>=2.32",
]

[project.urls]
Homepage = "https://github.com/ppak10/Agentic-Additive-Manufacturing-Process-Optimization"
Issues = "https://github.com/ppak10/Agentic-Additive-Manufacturing-Process-Optimization/issues"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"agentic_sls" = ["py.typed"]
